### ISSUE TITLE
System.Reflection.AmbiguousMatchException

### ISSUE THREAD

**Issue by phidiassj** [marthijn/Sidio.Sitemap.Blazor#4]
hello.

I tried using this library in my Blazor 8 hybrid project. I only added the @attribute [Sitemap] directive to a few pages. There were no errors during compilation and execution, but when I navigate to sitemap.xml, I encounter the following error. I would appreciate any suggestions anyone could provide!

System.Reflection.AmbiguousMatchException: Multiple custom attributes of the same type 'Microsoft.AspNetCore.Components.RouteAttribute' found.
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at Sidio.Sitemap.Blazor.SitemapMiddleware.CreateSitemap(IComponentBaseProvider componentBaseProvider)
   at Sidio.Sitemap.Blazor.SitemapMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by phidiassj** [comment]
Hi, Thanks for your reply.
I found that the problem came from I am using a custom component to redirect the 404 URL.

Routes.razor
`
<Router AppAssembly="typeof(Program).Assembly" AdditionalAssemblies="new[] { typeof(Client._Imports).Assembly }">
    <Found Context="routeData">
        <RouteView RouteData="routeData" DefaultLayout="typeof(Layout.MainLayout)" />
        <FocusOnNavigate RouteData="routeData" Selector="h1" />
    </Found>
    <NotFound>
        <PageTitle>Not found</PageTitle>
        <LayoutView Layout="@typeof(Layout.MainLayout)">
            <SidioSitemapBlazorTest.Components.Pages.NotFoundPage />
        </LayoutView>
    </NotFound>
</Router>
`

NotFoundPage.razor
`
@page "/pagenotfound"
@page "/pagenotfound/{httpcode}"
@inject IJSRuntime jsRuntime
@rendermode InteractiveServer

<h5 style="text-align:center;">This URL do not exist...Redirecting...</h5>

@code {
    [Parameter]
    public string? httpcode { get; set; }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            var uri = navManager.ToAbsoluteUri("/");
            int redirectAfterMs = 1000;

            await jsRuntime.InvokeVoidAsync("redirectToLocalUri", uri, redirectAfterMs);
        }
    }
}
`

**Comment by marthijn** [comment]
Thanks. I'll look into it next week.

**Comment by phidiassj** [comment]
Hello, I think I made a mistake, after further experimentation I discovered that the problem was not from custom components, but from multiple routes.
You only need to use more than one page attribute on the same component to cause this problem.
Some thing like:
```
@page "/pagenotfound"
@page "/pagenotfound/{httpcode}"
```

**Comment by marthijn** [comment]
@phidiassj the issue is fixed in release 1.0.2
